[Kubeconf]
Version = "1.18.5"
# 增加节点时要使用token 与证书hash值，部署时不必填写，部署完成后会回写配置文件。dashboard管理员token回写
Token = ""
CertHash = ""
DashboardToken = ""

[Node]
# 左边为节点hostname ，右边为对应的节点ip，默认添加上 `master` 关键字的会部署master的资源,如果都没添加，则从node随机挑3个节点。
"kubeadm" = "192.168.1.230"

[Ssh]
# ssh登陆端口，账号密码，请统一一个
Port = 22
# 用户名请默认填root
Username = "root"
# root密码
Password = "vagrant"
Pkeypass = ""